---
title: "Errore PGS-220000 PostgreSQL: la relazione \"t1\" non esiste"
description: Scopri come correggere l’errore generato dal flusso di lavoro di tracciamento dopo un recente aggiornamento della build 9343 o versione successiva in Adobe Campaign Classic v7.
solution: Campaign Classic v7
product: Campaign Classic v7
applies-to: "Campaign Classic v7"
keywords: "KCS, Campaign Classic, flusso di lavoro di tracciamento, nms:TrackingLog"
resolution: Resolution
internal-notes: null
bug: false
article-created-by: Amol Mahajan
article-created-date: "11/16/2023 10:39:55 AM"
article-published-by: Amol Mahajan
article-published-date: "11/16/2023 10:51:09 AM"
version-number: 4
article-number: KA-17530
dynamics-url: "https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=65d80679-6c84-ee11-8179-6045bd0065b6"
source-git-commit: 046fc70e66a1a9b196ffb0a1f2176846791a1aad
workflow-type: tm+mt
source-wordcount: '194'
ht-degree: 2%

---

# Errore PGS-220000 PostgreSQL: la relazione &quot;t1&quot; non esiste


Se ricevi un errore: `PGS-220000 PostgreSQL error: relation "t1" does not exist...,` generato dal flusso di lavoro di tracciamento in Adobe Campaign Classic v7, consulta questo articolo per scoprire come risolvere questo problema.

## Descrizione {#description}


### <b>Ambiente</b>

Campaign Classic v7



### <b>Problema/Sintomi</b>

Dopo un recente aggiornamento della build 9343 o versione successiva, il flusso di lavoro di tracciamento genera i seguenti errori:




```
nlmodule    PGS-220000 PostgreSQL error: ERROR:  relation "t1" does not exist LINE 1: ...t, T3.iArticle, T2.iType FROM NmsTrackingUrl T2,  T1 LEFT OU... nlmodule    WDB-200001 SQL statement 'SELECT T1.tsLog, T1.iDeliveryId, T1.iUrlId, T1.sSourceType, T3.dAmount, T3.iArticle, T2.iType FROM NmsTrackingUrl T2,  T1 LEFT OUTER JOIN NmsWebTrackingLog T3 ON iTrackingLogId = iWebTrackingLogId WHERE T1.tsLog < :#(1)# AND T1.tsLog >= :#(2)#  AND T1.iUrlId=T2.iTrackingUrlId ORDER BY T1.tsLog' could not be executed.   Param(0)=09/17/2020 8:55:00 PM   Param(1)=09/16/2020 8:55:00 PMnlmodule    Attribute 'broadLog-id' unknown (see definition of schema 'Tracking logs (nms:trackingLog)').
```





## Risoluzione {#resolution}


Dai registri di tracciamento dettagliati, si nota che il flusso di lavoro di tracciamento alla fine del consolidamento dei dati non riesce:




```
00000000 00000000 1 info log Consolidating tracking logs for the period [ 09/16/2020 3:55:00 PM, 09/17/2020 3:55:00 PM[ ...00000000 00000000 1 info wdbc Select: [ 00000000 ]  SELECT T1.tsLog, T1.iDeliveryId, T1.iUrlId, T1.sSourceType, T3.dAmount, T3.iArticle, T2.iType FROM NmsTrackingUrl T2, T1 LEFT OUTER JOIN NmsWebTrackingLog T3 ON iTrackingLogId = iWebTrackingLogId WHERE T1.tsLog < :#(1)# AND T1.tsLog >= :#(2)# AND T1.iUrlId=T2.iTrackingUrlId ORDER BY T1.tsLog00000000 00000000 2 info wdbc Param(0)=09/17/2020 8:55:00 PM00000000 00000000 2 info wdbc Param(1)=09/16/2020 8:55:00 PM00000000 00000000 1 error log PGS-220000 PostgreSQL error: ERROR: relation "t1" does not exist\nLINE 1: ...t, T3.iArticle, T2.iType FROM NmsTrackingUrl T2, T1 LEFT OU...\n \n. (iRc=-2006)00000000 00000000 1 error log WDB-200001 SQL statement 'SELECT T1.tsLog, T1.iDeliveryId, T1.iUrlId, T1.sSourceType, T3.dAmount, T3.iArticle, T2.iType FROM NmsTrackingUrl T2, T1 LEFT OUTER JOIN NmsWebTrackingLog T3 ON iTrackingLogId = iWebTrackingLogId WHERE T1.tsLog < :#(1)# AND T1.tsLog >= :#(2)# AND T1.iUrlId=T2.iTrackingUrlId ORDER BY T1.tsLog' could not be executed.\n Param(0)=09/17/2020 8:55:00 PM\n Param(1)=09/16/2020 8:55:00 PM (iRc=-2006)
```




Ogni volta che inizia il flusso di lavoro di tracciamento, richiama tutte le mappature di destinazione e aggiorna i dati in base alla configurazione.

In questo caso, il problema è causato da una mappatura di destinazione. Vedi di seguito:

![](assets/a06a8deb-6536-ec11-b6e6-000d3a348885.png)

Fondamentalmente,<b> NMS: registro di tracciamento</b> Lo schema NON deve essere utilizzato per monitorare i registri, perché lo schema non è correlato a una tabella di database (SQL).

In conclusione, il problema non ha nulla a che fare con l&#39;aggiornamento, ma più con una configurazione di mappatura di destinazione errata.
